apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
#put IP of the nfs-server container
    server: 10.1.3.116
    path: "/mnt/volumes"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-client
spec:
  replicas: 1
  selector:
    role: nfs-server
  template:
    metadata:
      name: mpi-scheduler
      labels:
        role: nfs-server
        name: mpi-scheduler
    spec:
      automountServiceAccountToken: false
      hostname: mpi-scheduler
      subdomain: mpi-cluster
      dnsConfig:
        searches:
        - mpi-cluster.default.svc.cluster.local
      containers:
      - name: mpi-scheduler
        image: hannahnw124/slurm_sing_nfs
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
#Change privileged?
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: "/home"
            name: nfs-vol-storage
      volumes:
        - name: nfs-vol-storage
          persistentVolumeClaim:
            claimName: nfs-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: mpi-worker-0
  labels:
    name: mpi-worker
spec:
  hostname: mpi-worker-0
  subdomain: mpi-cluster
  dnsConfig:
    searches:
    - mpi-cluster.default.svc.cluster.local
  containers:
  - image: hannahnw124/slurm_sing_nfs
    name: mpi-worker
    securityContext:
      privileged: true
---
apiVersion: v1
kind: Pod
metadata:
  name: mpi-worker-1
  labels:
    name: mpi-worker
spec:
  hostname: mpi-worker-1
  subdomain: mpi-cluster
  dnsConfig:
    searches:
    - mpi-cluster.default.svc.cluster.local
  containers:
  - image: hannahnw124/slurm_sing_nfs
    name: mpi-worker
    securityContext:
      privileged: true
---
apiVersion: v1
kind: Pod
metadata:
  name: mpi-worker-2
  labels:
    name: mpi-worker
spec:
  hostname: mpi-worker-2
  subdomain: mpi-cluster
  dnsConfig:
    searches:
    - mpi-cluster.default.svc.cluster.local
  containers:
  - image: hannahnw124/slurm_sing_nfs
    name: mpi-worker
    securityContext:
      privileged: true
---
apiVersion: v1
kind: Pod
metadata:
  name: mpi-worker-3
  labels:
    name: mpi-worker
spec:
  hostname: mpi-worker-3
  subdomain: mpi-cluster
  dnsConfig:
    searches:
    - mpi-cluster.default.svc.cluster.local
  containers:
  - image: hannahnw124/slurm_sing_nfs
    name: mpi-worker
    securityContext:
      privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server-service
spec:
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
    - name: mountd
      port: 20048
      targetPort: 20048
    - name: rpcbind
      port: 111
      targetPort: 111
  selector:
    role: nfs-server
---
apiVersion: v1
kind: Service
metadata:
  name: mpi-cluster
spec:
  selector:
    name: mpi-worker
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: mpi-scheduler
spec:
  selector:
    name: mpi-scheduler
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
